# Generated by Django 2.1.5 on 2020-06-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200613_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Technology'), ('2', 'Health'), ('3', 'Sports'), ('4', 'International'), ('5', 'National')], max_length=1)),
                ('headline', models.ManyToManyField(to='news.Headline')),
            ],
        ),
    ]
